name: 'Export Managed Dynamics 365 Solution'
description: 'This Github Action exports your managed solution and outputs you the file that contains your solution.'
branding:
  icon: 'arrow-up-right'
  color: 'blue'
outputs:
  exported_file_path:
    description: 'Path to the exported solution file'
    value: ${{ steps.export-changes.outputs.exported_file_path }}
  exported_file_base64:
    description: 'Path to the exported solution file'
    value: ${{ steps.export-changes.outputs.exported_file_base64 }}
inputs:
    dynamics-url:
        description: 'The URL of your Microsoft Dynamics instance'
        required: true
    application-id:
        description: 'The Application ID of your Azure AD application connected to your Microsoft Dynamics instance app user'
        required: true
    application-secret:
        description: 'The Application Secret of your Azure AD application connected to your Microsoft Dynamics instance app user'
        required: true
    tenant-id:
        description: 'The Tenant ID of your Azure AD application connected to your Microsoft Dynamics instance app user'
        required: true
    solution-name:
        description: 'The name of the solution you want to export'
        required: true
    version-number:
        description: 'The version number you want to assign to this version of the solution. If left blank, a new solution version will not be cloned.'
        required: false
runs:
  using: "composite"
  steps:

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Dependencies
      shell: bash
      run: composer install -d "$GITHUB_ACTION_PATH/src/" -o

    - name: Publish all changes
      id: export-changes
      shell: bash
      env:
        INSTANCE_URL: ${{ inputs.dynamics-url }}
        APPLICATION_ID: ${{ inputs.application-id }}
        APPLICATION_SECRET: ${{ inputs.application-secret }}
        TENANT_ID: ${{ inputs.tenant-id }}
      run: |
        output=$(php "$GITHUB_ACTION_PATH/src/index.php" "${{ inputs.solution-name }}" "${{ github.action_path }}" "${{ inputs.version-number }}")
        filepath=$(echo $output | cut -d'|' -f1)
        base64=$(echo $output | cut -d'|' -f2)
        echo "exported_file_path=$filepath" >> $GITHUB_OUTPUT
        echo "exported_file_base64=$base64" >> $GITHUB_OUTPUT
        
